import jsPDF from "jspdf";
import type { DecodeResult, ResumeGapResult } from "@/types/jd";

export const generateUnifiedReport = (jdResults: DecodeResult, resumeResults?: ResumeGapResult | null) => {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // -- Helper: Branded Header --
  const addHeader = (title: string, subtitle?: string) => {
    doc.setFillColor(16, 185, 129); // Lumina Teal
    doc.rect(0, y - 5, pageWidth, 2, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(10, 10, 10);
    doc.text(title, 20, y + 8);
    
    if (subtitle) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(subtitle.toUpperCase(), 20, y + 14);
    }
    y += 25;
  };

  // -- Section 1: JD Intelligence --
  addHeader("JD Intelligence Report", `Score: ${jdResults.grade.score}% | ${jdResults.logistics.salary_range.currency} ${jdResults.logistics.salary_range.min.toLocaleString()} - ${jdResults.logistics.salary_range.max.toLocaleString()}`);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 10);
  doc.text("Professional Verdict:", 20, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  jdResults.grade.plain_english_summary.forEach(point => {
    const lines = doc.splitTextToSize(`• ${point.replace(/\*\*/g, "")}`, pageWidth - 40);
    doc.text(lines, 20, y);
    y += lines.length * 5 + 2;
  });

  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text("Critical Vulnerabilities (Red Flags):", 20, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  jdResults.red_flags.forEach(flag => {
    const text = `! ${flag.phrase}: ${flag.note}`;
    const lines = doc.splitTextToSize(text, pageWidth - 40);
    doc.text(lines, 20, y);
    y += lines.length * 5 + 2;
  });

  // -- Section 2: Resume Alignment (If available) --
  if (resumeResults) {
    if (y > 200) { doc.addPage(); y = 20; }
    else y += 15;

    addHeader("Performance Match Analysis", `Overall Alignment: ${resumeResults.overall_match}%`);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Strategic Alignment Summary:", 20, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const summaryLines = doc.splitTextToSize(resumeResults.summary, pageWidth - 40);
    doc.text(summaryLines, 20, y);
    y += summaryLines.length * 5 + 5;

    doc.setFont("helvetica", "bold");
    doc.text("Top Action Directives:", 20, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    (resumeResults.actionable_directives || []).forEach((d, i) => {
      doc.text(`${i + 1}. ${d.action}: ${d.description}`, 20, y);
      y += 6;
    });
  }

  // -- Footer --
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Lumina AI Career Engine | Private & Confidential", pageWidth / 2, 285, { align: "center" });

  doc.save(`Lumina-Intelligence-Report-${new Date().getTime()}.pdf`);
};
