project_id = "esjzitabjftwiqjzjttw"

[functions.cover-letter]
verify_jwt = true

[functions.generate-roadmap]
verify_jwt = true

[functions.embed]
verify_jwt = true

[functions.diagnose]
verify_jwt = false
